baseURL = "https://buddhism.fun/"
languageCode = "en-us"
title = 'Li Ying Apps'
theme = "hugo-ficurinia-master"


[params]
showTags = false
showRss = false
enableSearch = false
logo = "/smile.png"
favicon = "/smile.png"